spring.datasource.url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=Europe/Moscow
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect